# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Enter vapor_ws_server
    - run: cd vapor_ws_server
    - uses: actions/checkout@v3
    - name: Build Vapor WS Server
    - run: swift build -v
    - name: Text Vapor WS Server
    - run: swift test -v
    - name: Enter Vapor WS Client
    - run: cd ../vapor_ws_client/
    - name: Build Vapor WS Client
    - run: swift build -v
    - name: Test Vapor WS Client
    - run: swift test -v
